#!/usr/bin/python

from __future__ import absolute_import, print_function, unicode_literals

import dbus
import json

bus = dbus.SystemBus()
response = {"isPowerOn": 0, "isDeviceDetected": 0}

manager = dbus.Interface(bus.get_object("org.bluez", "/"),
					"org.freedesktop.DBus.ObjectManager")

objects = manager.GetManagedObjects()

for path, interfaces in objects.iteritems():
	if "org.bluez.Adapter1" not in interfaces.keys():
		continue
	properties = interfaces["org.bluez.Adapter1"]
	response["isDeviceDetected"] = 1
	response["isPowerOn"] = properties["Powered"]
	break

print(json.dumps(response))
